---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == 'Debian'

- name: install apache packages
  package:
    name: '{{ apache_packages }}'
    state: '{{ apache_packages_state }}'

- name: apache remove default vhost
  file:
    path: '{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}'
    state: absent
  when: ansible_os_family == 'Debian'
